name: Deploy Databricks Asset Bundle

on:
  push:
      branches:
        - main

jobs:
  deploy:
  steps:
    -name: checkout code
    uses: actions/checkout@v4
    with:
      working-directory: ./health_dab
      databricks-host: https://adb-7405606749419928.8.azuredatabricks.net
      databricks-bundle-env: prod
      authentication-type: token
      databricks-token: ${{secrets.DATABRICKS_TOKEN}}}
      
    
